name: Release pull request

on:
  release:
    types: [released, prereleased]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      # - name: Get release version
      #   uses: actions/github-script@v6
      #   run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Get release version
        uses: actions/github-script@v6
        id: version
        with:
          script: |
            const tag = context.ref.substring(10)
            core.setOutput("tag", tag)

      - name: Create promotion branch
        run: |
          git checkout -B release/${{ steps.version.outputs.tag }}
          git push --set-upstream origin release/${{ steps.version.outputs.tag }}
          git fetch origin develop:develop
          git reset --hard develop

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          branch: release/${{ steps.version.outputs.tag }}
          title: Release ${{ steps.version.outputs.tag }}
          body: |
            Merge this PR to release ${{ steps.version.outputs.tag }} to production.
          assignees: benyap
