name: Release pull request

on:
  release:
    types: [published]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Reset promotion branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: release
          branch: develop
          base: main
