name: Release pull request

on:
  release:
    types: [published]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Get release version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo ${{ env.RELEASE_VERSION }}

      - name: Create promotion branch
        run: |
          git checkout -B release/${{ env.RELEASE_VERSION }}
          git push --set-upstream origin release/${{ env.RELEASE_VERSION }}
          git fetch origin develop:develop
          git reset --hard develop

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          branch: release/${{ env.RELEASE_VERSION }}
          title: Release ${{ env.RELEASE_VERSION }}
          body: Merge this PR to release ${{ env.RELEASE_VERSION }} to production.
          labels: enhancement
          assignees: benyap
