name: Release pull request

on:
  release:
    types: [released, prereleased]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get release version
        uses: actions/github-script@v6
        id: version
        with:
          script: |
            const release = context.ref.substring(10)
            const releaseType = release.replace(/^(\d+\.)+\d+-?/, "").replace(/\.\d+$/, "")
            core.setOutput("release", release)
            core.setOutput("releaseType", releaseType || "latest")

      - name: Run test command
        run: echo public --tag ${{ steps.version.outputs.releaseType }}

      - name: Create release branch
        run: |
          git checkout -B release/${{ steps.version.outputs.release }}
          git push --set-upstream origin release/${{ steps.version.outputs.release }}

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: release/${{ steps.version.outputs.release }}
          target_branch: main
          get_diff: true
          title: Release ${{ steps.version.outputs.release }}
          body: |
            ### Summary
            Merge this PR to release ${{ steps.version.outputs.release }} to production.

            **Release version:** ${{ steps.version.outputs.release }}
            **Release type:** ${{ steps.version.outputs.releaseType }}

            ### Commits
            <!-- Diff commits - START -->
            <!-- Diff commits - END -->
